/**
 * Enforce 100% line coverage on source files (src/).
 *
 * Reads the LCOV report generated by `bun test --coverage` and exits non-zero
 * if any source file is below 100% line coverage, or if coverage is missing.
 */
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

const lcovPath = join(import.meta.dir, '..', 'coverage', 'lcov.info');

try {
  const data = await readFile(lcovPath, 'utf8');
  const files = data.split(/(?=SF:)/g).filter(Boolean);

  let failed = false;
  let sourceFiles = 0;

  for (const block of files) {
    const sfMatch = block.match(/^SF:(.+)$/m);
    if (!sfMatch) continue;
    const file = sfMatch[1];
    // Only enforce coverage for source files, not tests or the coverage report itself.
    if (!file.startsWith('src/')) continue;
    sourceFiles++;

    const lines = block.match(/^DA:(\d+),(\d+)/gm) ?? [];
    const total = lines.length;
    const hit = lines.filter(l => !l.endsWith(',0')).length;
    const pct = total === 0 ? 100 : Math.round((hit / total) * 1000) / 10;

    if (pct < 100) {
      failed = true;
      const uncovered = lines.filter(l => l.endsWith(',0')).map(l => l.split(':')[1].split(',')[0]);
      console.error(`FAIL: ${file} line coverage ${pct}% (${uncovered.join(', ')})`);
    } else {
      console.log(`OK:   ${file} ${pct}%`);
    }
  }

  if (sourceFiles === 0) {
    console.error('FAIL: no source files found in coverage report — did coverage run?');
    process.exit(1);
  }

  if (failed) {
    process.exit(1);
  }
  console.log('\nAll source files at 100% line coverage.');
} catch (e) {
  console.error('Could not read coverage report:', (e as Error).message);
  console.error('Run `bun test --coverage` first.');
  process.exit(1);
}
